In [1]:
import pandas as pd

In [2]:
file_path = "/Users/jakegehrung/Desktop/data_raw/data_processed/fintry_epc_number_floor_update.csv"

df = pd.read_csv(file_path)

In [3]:
df.head()

,BUILDING_REFERENCE_NUMBER,OSG_REFERENCE_NUMBER,ADDRESS1,ADDRESS2,ADDRESS3,POSTCODE,LATITUDE,LONGITUDE,INSPECTION_DATE,TYPE_OF_ASSESSMENT,...,RIDGE_TO_ATTIC_HEIGHT,HALF_WALL_WIDTH,ROOF_WIDTH,HALF_ROOF_AREA,ROOF_AREA,USABLE_ROOF_LENGTH,USABLE_ROOF_WIDTH,PANELS_ALONG_LENGTH,PANELS_ALONG_WIDTH,POSSIBLE_PV_PANELS
0,1001829067,122009933.0,19 CULCREUCH AVENUE,FINTRY,GLASGOW,G63 0YB,56.055692,-4.223337,9/29/25,"RdSAP, existing dwelling",...,2.291288,2.291288,3.240370,14.849242,29.698485,3.895189,2.754315,2,2,0
1,1001951858,122010025.0,GLENVIEW,FINTRY,GLASGOW,G63 0XJ,56.052824,-4.220640,9/19/25,"RdSAP, existing dwelling",...,3.240370,3.240370,4.582576,44.547727,89.095454,8.262944,3.895189,4,3,8
2,1001829071,122009868.0,22 CULCREUCH AVENUE,FINTRY,GLASGOW,G63 0YB,56.055503,-4.223691,7/29/25,"RdSAP, existing dwelling",...,2.915476,2.915476,4.123106,24.041631,48.083261,4.956309,3.504640,2,3,2
3,1234761001,122009968.0,1 MENZIES TERRACE,FINTRY,GLASGOW,G63 0YJ,56.058427,-4.224838,7/22/25,"RdSAP, existing dwelling",...,3.253204,3.253204,4.600725,44.901281,89.802561,8.295669,3.910616,4,3,8
4,1001991633,122009892.0,50 MAIN STREET,FINTRY,GLASGOW,G63 0XF,56.054738,-4.228307,7/17/25,"RdSAP, existing dwelling",...,6.563332,4.163332,7.772429,97.077613,194.155227,10.616497,6.606565,5,5,21

In [4]:
df.columns

Index(['BUILDING_REFERENCE_NUMBER', 'OSG_REFERENCE_NUMBER', 'ADDRESS1',
       'ADDRESS2', 'ADDRESS3', 'POSTCODE', 'LATITUDE', 'LONGITUDE',
       'INSPECTION_DATE', 'TYPE_OF_ASSESSMENT',
       ...
       'RIDGE_TO_ATTIC_HEIGHT', 'HALF_WALL_WIDTH', 'ROOF_WIDTH',
       'HALF_ROOF_AREA', 'ROOF_AREA', 'USABLE_ROOF_LENGTH',
       'USABLE_ROOF_WIDTH', 'PANELS_ALONG_LENGTH', 'PANELS_ALONG_WIDTH',
       'POSSIBLE_PV_PANELS'],
      dtype='object', length=219)

In [5]:
df["FOOTPRINT_AREA"] = df["TOTAL_FLOOR_AREA"] / df["NUMBER_OF_FLOORS"]

In [6]:
df[["TOTAL_FLOOR_AREA", "NUMBER_OF_FLOORS", "FOOTPRINT_AREA"]].head()

   TOTAL_FLOOR_AREA  NUMBER_OF_FLOORS  FOOTPRINT_AREA
0                42                 2            21.0
1               126                 2            63.0
2                68                 2            34.0
3               127                 2            63.5
4               104                 1           104.0

In [7]:
df["FOOTPRINT_AREA"] = df["TOTAL_FLOOR_AREA"] / df["NUMBER_OF_FLOORS"]
df["FOOTPRINT_AREA"] = df["FOOTPRINT_AREA"].replace([float("inf"), -float("inf")], pd.NA)

In [8]:
output_path = "/Users/jakegehrung/Desktop/data_raw/data_processed/fintry_epc_footprint_update.csv"

df.to_csv(output_path, index=False)

In [9]:
df["FOOTPRINT_AREA"].describe()

count    117.000000
mean      65.669516
std       31.692216
min       21.000000
25%       38.500000
50%       63.500000
75%       85.500000
max      212.500000
Name: FOOTPRINT_AREA, dtype: float64